# Generated by Django 2.1.4 on 2019-11-12 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='batchNum',
            field=models.IntegerField(default=''),
        ),
    ]
