# Generated by Django 2.1.4 on 2019-11-12 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20191112_0232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='batchNum',
            field=models.IntegerField(default=0),
        ),
    ]
